import("//build/ohos.gni")

ohos_shared_library("libhook_anymem") {
  sources = [ "malloc_free_hook.c" ]

  cflags = [
    "-fPIC",
    "-Wall",
    "-Wextra",
    "-Werror",
  ]

  ldflags = [ "-Wl,--no-undefined" ]
}

ohos_executable("libmini_replay_main") {
  sources = [ "replay_main.c" ]

  cflags = [
    "-O3",
    "-DNDEBUG",
    "-Wall",
    "-Wextra",
  ]

  ldflags = [ "-pthread" ]
}